### ISSUE TITLE
System boot stuck after patched firmware application

### ISSUE THREAD

**Issue by ElectricWound** [fred41/G940-firmware-fixes#2]
Hi Fred41,
thank's a million for providing this excellent fix for the G940 axis behavior. Unfortunately after applying the firmware fix respecting the whole driver upgrade procedure, of course, I am encountering very strange system boot behavior when cold starting the PC. When the system starts and the G940 is attached to a USB port, the boot hangs until I unplug the G940. This was not apparent before the firmware update. I use an Asus Sabertooth X79 with a Core-i7 3930k @4GHz and an 850W PSU. If I attach the G940 after Windows has booted, everything is working as expected. Did the firmware modification probably change any of the start up code, thus changing tolerances or timing, such that USB handshake might fail. I do not know, whether there's a way to provide any kind of log data to provide any insight in what's happening. Any help on this would be very much appreciated.
Thanks for all your effort.
Henning

**Comment by fred41** [comment]
I remember to got this problem too, but didn't investigate it for now. I changed some loops to unload the arm controller a bit, what may changed some timings at boot. I will check this out if i find the time.

**Comment by fred41** [comment]
Should be solved, since i removed this optimization. Please check and let me know.

**Comment by fred41** [comment]
... solved ...

**Comment by ElectricWound** [comment]
Sorry for commenting late, I was off gaming for a while and did not have an opportunity to test. As far as I can tell from a handful of startup, boot seems to be stable now. Thanks for fixing this.

There's one new issue since the patch, but I am not sure, how to prove it. I have the impression, that the startup "shock" of the stick, when the center force kicks in for the first time when booting,  is somewhat "harder". I have checked on the driver settings and all force sliders are at their normal 100% position.

And another question: Do I have to re-calibrate the axis in the driver after patching? Are there any driver settings that might accidentlöy "undo" your awesome hysteresis improvements?

**Comment by fred41** [comment]
Are you sure you did the patching process correctly (...just do it again in case...)?
There should be a hysteresis setting in the windows driver, ensure it is set to minimum.
I think recalibrating is always a good idea, but i dont know, what logic is implemented in it's windows driver.
