### ISSUE TITLE
Unable to compile with the same size

### ISSUE THREAD

**Issue by angelivorra** [fred41/G940-firmware-fixes#3]
Hi. I am in widows 10.

I am trying to compile this amazing pieze of software beacuse i need some modifications.

I tried with MiniGW and the exe size is 70kb aprox.

I tried with Visual Studio, and the exe is 110k

Whan do you use to compile?

Thanks.

**Comment by fred41** [comment]
Hi, i used visual studio express (2010) to build the patch as a console app.
I would highly recommend, to connect a SWD debugging probe (st-link v2) to the G940 first, to be able to recover the firmware, in case you did something wrong. There are some unused pins on the PCB near the stm32 for this purpose.

**Comment by fred41** [comment]
... looks like fixed ...
