### ISSUE TITLE
Loss of Trim1 and Trim 2

### ISSUE THREAD

**Issue by bortglomd** [fred41/G940-firmware-fixes#4]
After installing the update, Trim 1 And Trim 2 on the joystick no longer works.

**Comment by fred41** [comment]
This is the first report of such a problem. Are this controls working again if you apply the original (unpatched) 1.42 again?

**Comment by bortglomd** [comment]
Hi fred. No, it did not work. I was able to get all controls back by installing the G940 patch released by Logitech. I then applied ur patch after that and it worked. I guess i lost trim before is because I was running my G940 without any programs before, i just plugged and played, and installed ur update.

**Comment by fred41** [comment]
Ok, thanks for your feedback. I am going to close this issue now.
