### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by Leesyu** [fred41/G940-firmware-fixes#5]
hello ，i am a dcs player using g940,
after using this fixes i have a pronlem and an advice to you
my problem is after using this fixes ,my joystick always shakes hardly in center ,if you can gave me your e-mail address ,i'll send the video of this to you.
my advice is G940 joystick has a physics center for example 50 of 0 to 100 ,and in dcs there is anoter virtual center whitch is not in 50 ,for example 70. in dcs joystick in 70 location is forceless when my hand on it ,however after my hand leave  the joystick ,it go back to 50 immediately ,i have to put my hand on joystick all time and can't use mouse at all. could you please solve this please?
thank you all the time

**Comment by fred41** [comment]
What you describe, is normal behavoir for G940.
Some peoples are covering the optical sensor with tape, to simulate 'hand on stick', maybe this help you too?
