### ISSUE TITLE
possibility to revert back to the official patch?

### ISSUE THREAD

**Issue by r-flo-r** [fred41/G940-firmware-fixes#6]
hi. thanks for the software. looking forward to apply the updated firmware. but i wanted to ask, if i can roll back to the last official patch of logitech, if anything goes wrong with your patch or does not work as intended on my side. thanks

**Comment by unhappytroll** [comment]
iirc, you can just reflash it with original firmware, and that's it. thinking of it, you must first flash a last original firmware anyway.

**Comment by r-flo-r** [comment]
thanks. issue will be closed.
